import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useChannel, useEvent } from '@harelpls/use-pusher';
import { useState } from 'react';

const Home: NextPage = () => {
    const [message, setMessages] = useState([]);
    const data = ['Element 1', 'Element 2', 'Element 3'];

    const channel = useChannel('my-channel');
    useEvent(channel, 'my-event2', ({ data }) => {
        console.log('recieved ', data);
        setMessages((messages) => [...messages, data]);
    });
    return (
        <div className={styles.container}>
            <Head>
                <title>Guidance App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Work station 1</h1>
                <p>message: {message}</p>
                <p className={styles.description}>List of tasks </p>
                {message.map((element, index) => (
                    <div className={styles.grid} key={index}>
                        <h2 className={styles.card}> {element}</h2>
                    </div>
                ))}
                <p className={styles.description}>Images </p>
            </main>
        </div>
    );
};

export default Home;
