import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import DropzoneForm from '../components/DropzoneForm';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Guidance App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Production Control Station</h1>
                <p className={styles.description}>Live Status </p>
                <>
                    <Image
                        alt="Mountains"
                        src={   
                            'https://media1.giphy.com/media/7On8JCPlFnN5Q6ApYL/giphy.gif?cid=ecf05e47csxyb36ykuqbr85kkbrw2rijcq2vn3yb79v6bahd&ep=v1_gifs_search&rid=giphy.gif&ct=g'
                        }
                        width={400}
                        height={275}
                        // sizes="50vw"
                        style={{
                            width: '100%',
                            height: 'auto',
                        }}
                    />
                </>
                <p className={styles.description}>
                    Upload Resources (Image or PDF)
                </p>

                <DropzoneForm />
            </main>
        </div>
    );
};

export default Home;
